name: Run Playwright Tests

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      
      # Step 1: Checkout of repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: browsers for Playwright
      - name: Install Playwright browsers
        run: npx playwright install

      # Step 5:  TypeScript
      - name: Compile TypeScript
        run: npx tsc --noEmit

      # Step 6: Launch Playwright
      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      
      # Step 7: Upload test report
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report
      

      

        

